"""updated _password_hash by removing nullable constraint

Revision ID: 170656422d24
Revises: e01c1abae1b8
Create Date: 2024-05-03 11:14:46.454770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170656422d24'
down_revision = 'e01c1abae1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
